### ISSUE TITLE
any idea to visualise retreived graph and integrate in streamlit?

### ISSUE THREAD

**Issue by ruiguo-bio** [neo4j-graphacademy/llm-chatbot-python#17]
Hello. Thanks for this course. Can I have some guidance how to integrate an interactive visual interface (like the neo4j) of the retrieved graph into the chatbot interface? Thanks

**Comment by martinohanlon** [comment]
I dont have any specific advice re interfaces and integration with streamlit. This blog post talks through 15 different options for visualisation - https://neo4j.com/developer-blog/15-tools-for-visualizing-your-neo4j-graph-database/

I would also reach out to the Neo4j community at https://community.neo4j.com/ where you can reach a much bigger audience.
