### ISSUE TITLE
Agent using tool failed to add output into memory

### ISSUE THREAD

**Issue by skywateryang** [neo4j-graphacademy/llm-chatbot-python#4]
By following the course "[Build a Neo4j-backed Chatbot using Python](https://graphacademy.neo4j.com/courses/llm-chatbot-python/)", when running the code to use agent to call vector search tool, it triggered such error.

Traceback (most recent call last):
  File "/Users/skywater/PycharmProjects/pythonProject/KG_LLM/llm-chatbot-python/tets.py", line 121, in <module>
    response = agent_executor.invoke({"input": prompt})
  File "/Users/skywater/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/langchain/chains/base.py", line 164, in invoke
    final_outputs: Dict[str, Any] = self.prep_outputs(
  File "/Users/skywater/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/langchain/chains/base.py", line 440, in prep_outputs
    self.memory.save_context(inputs, outputs)
  File "/Users/skywater/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/langchain/memory/chat_memory.py", line 39, in save_context
    self.chat_memory.add_ai_message(output_str)
  File "/Users/skywater/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/langchain_core/chat_history.py", line 65, in add_ai_message
    self.add_message(AIMessage(content=message))
  File "/Users/skywater/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 107, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for AIMessage
content
  str type expected (type=type_error.str)
content
  value is not a valid list (type=type_error.list)

As I troubleshooted, found the error was due to the output is a dict format, something like 
{'query': query, 'result':result}, rather than string, making it failed to add in memory.
I think my code is exactly same with courses and this repo, anyone knows the reason and how to solve it.
My langchain version is 0.1.1

**Comment by miquelmongeAZ** [comment]
I've got the exact same error. It seems the code of the course is out-of-date. Also to add another error, using the react-chat agent (the one that the course use), it expect also the "chat_history" input.

Do you have manage to solve it?

**Comment by skywateryang** [comment]
> I've got the exact same error. It seems the code of the course is out-of-date. Also to add another error, using the react-chat agent (the one that the course use), it expect also the "chat_history" input.
> 
> Do you have manage to solve it?

@miquelmongeAZ 
I solved it by changing 'kg_qa' to 'kg_qa.run' in the step of adding tools
    Tool.from_function(
        name="Vector Search Index",  
        description="Provides information about movie plots using Vector Search",  
        func=kg_qa.run,  
        return_direct=True
    )

**Comment by AntoninJuquel** [comment]
Hello I solved this issue by settting `return_direct=False` and adding `handle_parsing_error=True` to every tools in the `agent.py` file.
Here is my tools list with the changes:
```py
tools = [
    Tool.from_function(
        name="General Chat",
        description="For general chat not covered by other tools",
        func=llm.invoke,
        return_direct=False, # (!)
        handle_parsing_errors=True # (!)
    ),
    Tool.from_function(
        name="Cypher QA",
        description="Provide information about movies questions using Cypher",
        func = cypher_qa,
        return_direct=False, # (!)
        handle_parsing_errors=True # (!)
    ),
    Tool.from_function(
        name="Vector Search Index",
        description="Provides information about movie plots using Vector Search",
        func = kg_qa,
        return_direct=False, # (!)
        handle_parsing_errors=True # (!)
    )
]
```

Here is the result:

![image](https://github.com/neo4j-graphacademy/llm-chatbot-python/assets/57025128/a4802068-5aac-41ae-bf43-1ac2aa44e837)

![image](https://github.com/neo4j-graphacademy/llm-chatbot-python/assets/57025128/af9db39f-6a07-465e-8bb3-e5eaea63f687)

**Comment by martinohanlon** [comment]
Thanks for raising the issue. 

The course has been recently updated to reflect changes in Langchain v0.2 and the code to manage agents and tools updated.

Closing as no longer relevant.
